package hongik.ce.jolup.domain.accounts;

import lombok.*;

import javax.persistence.*;

@Entity
@Builder
@Getter
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(of = "id")
public class Account {
    /*
    create table account(
    id bigint generated by default as identity,
    username varchar(255) not null,
    password varchar(255) not null,
    email varchar(255) not null,
    role enum('USER', 'MANAGER', 'ADMIN') not null,
    primary key(id)
    );
    */
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String username;

    private String password;

    private String email;

    @Enumerated(EnumType.STRING)
    private AccountRole role;
}
