spring:
  datasource:
    url: jdbc:h2:file:./test;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate:
      SQL: debug
      type.descriptor.sql.BasicBinder: trace

server:
  servlet:
    session:
      timeout: 600
  tomcat:
    max-http-form-post-size: 5MB