spring:
  profiles:
    active: local-db
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 5MB

# local
#file:
#  path: C:/Users/user/Desktop/file/

# Aws EC2
file:
  path: /home/ubuntu/images/