package hongik.ce.jolup.domain.rooms;

import hongik.ce.jolup.domain.accounts.Account;
import lombok.*;

import javax.persistence.*;

@Getter
@Setter
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class JoinRoom {
    /*
    drop table if exists join_room CASCADE;
    create table join_room(
    join_room_id bigint generated by default as identity,
    user_id bigint,
    room_id bigint,
    room_role enum('MASTER', 'MANGER', 'GUEST') not null,
    primary key(join_room_id),
    foreign key(user_id) references account(user_id),
    foreign key(room_id) references room(room_id)
    );
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "join_room_id")
    private Long id;

    @ManyToOne
    @JoinColumn(name = "user_id")
    private Account account;

    @ManyToOne
    @JoinColumn(name = "room_id")
    private Room room;

    @Column(nullable = false)
    private RoomRole roomRole;
}
