package hongik.ce.jolup.domain.rooms;

import hongik.ce.jolup.domain.accounts.Account;
import lombok.*;

import javax.persistence.*;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Room {
    /*
    drop table if exists room CASCADE;
    create table room(
    room_id bigint generated by default as identity,
    subject varchar(255) not null,
    room_type enum('LEAGUE', 'TOURNAMENT') not null,
    user_id bigint,
    primary key(room_id),
    foreign key(user_id) references account(user_id)
    );
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "room_id")
    private Long id;

    @Column(nullable = false)
    private String subject;

    @Column(nullable = false)
    private RoomType roomType;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private Account account;
}
