package hongik.ce.jolup.domain.rooms;

import lombok.*;

import javax.persistence.*;

@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Room {
    /*
    drop table if exists room CASCADE;
    create table room(
    room_id bigint generated by default as identity,
    subject varchar(255) not null,
    room_type enum('LEAGUE', 'TOURNAMENT') not null,
    mem_num bigint not null,
    primary key(room_id)
    );
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "room_id")
    private Long id;

    @Column(nullable = false)
    private String subject;

    @Column(nullable = false)
    private RoomType roomType;

    @Column(nullable = false)
    private Long memNum;
}
