package hongik.ce.jolup.domain.join;

import hongik.ce.jolup.domain.room.Room;
import hongik.ce.jolup.domain.user.User;
import lombok.*;

import javax.persistence.*;

@Getter
@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(name = "joins")
public class Join {
    /*
    drop table if exists join_room CASCADE;
    create table join_room(
    join_room_id bigint generated by default as identity,
    user_id bigint,
    room_id bigint,
    room_role enum('MASTER', 'MANGER', 'GUEST') not null,
    primary key(join_room_id),
    foreign key(user_id) references account(user_id),
    foreign key(room_id) references room(room_id)
    );
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "join_id")
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id")
    private User user;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id")
    private Room room;

    /*@Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private JoinRole role;*/

    @Builder
    public Join(Long id, User user, Room room/*, JoinRole role*/) {
        this.id = id;
        this.user = user;
        this.room = room;
        /*this.role = role;*/
    }

    public void delete() {

    }
    /*public Join update(JoinRole role) {
        this.role = role;
        return this;
    }*/
}
