package hongik.ce.jolup.domain.join;

import hongik.ce.jolup.domain.Time;
import hongik.ce.jolup.domain.result.Result;
import hongik.ce.jolup.domain.competition.Competition;
import hongik.ce.jolup.domain.member.Member;
import hongik.ce.jolup.dto.JoinDto;
import lombok.*;

import javax.persistence.*;

@Getter
@Entity
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(name = "joins")
@ToString
public class Join extends Time {
    /*
    drop table if exists join_competition CASCADE;
    create table join_competition(
    join_competition_id bigint generated by default as identity,
    user_id bigint,
    competition_id bigint,
    competition_role enum('MASTER', 'MANGER', 'GUEST') not null,
    primary key(join_competition_id),
    foreign key(user_id) references account(user_id),
    foreign key(competition_id) references competition(competition_id)
    );
    */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "join_id")
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    private Member member;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "competition_id")
    private Competition competition;

    @Embedded
    private Result result;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private JoinRole joinRole;

    @Builder
    public Join(Long id, Member member, Competition competition, Result result, JoinRole joinRole) {
        this.id = id;
        if (member != null) {
            changeMember(member);
        }
        if (competition != null) {
            changeCompetition(competition);
        }
        this.result = result;
        this.joinRole = joinRole;
    }

    public JoinDto toDto () {
        return JoinDto.builder()
                .id(id)
                .memberDto(member.toDto())
                .competitionDto(competition.toDto())
                .result(result)
                .joinRole(joinRole)
                .build();
    }

    public Join update(Result result) {
        this.result = result;
        return this;
    }

    public void changeMember(Member member) {
        this.member = member;
        member.getJoins().add(this);
    }

    public void changeCompetition(Competition competition) {
        this.competition = competition;
        competition.getJoins().add(this);
    }
}
